name: Todo Service CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - "todo-service/**"
  pull_request:
    branches: [ main ]
    paths:
      - "todo-service/**"

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd todo-service
          npm ci

      - name: Syntax check
        run: node --check todo-service/index.js

      - name: Run tests
        run: |
          cd todo-service
          npm test

  deploy-docker:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: todo-service
          file: todo-service/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/todo-service:latest
            ${{ secrets.DOCKER_USERNAME }}/todo-service:${{ github.sha }}
